title: AYoung Park
iconURL: assets/logo_pig_박아영-02.jpg
# theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  blog: _velog.io/@ay_park
  github: ayoungparkme

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
# math latex
markdown : kramdown
highlighter : rouge
lsi : false
exceprpt_separator : "\n\n"
incremental : false

### comments & analytics
google_analytics: UA-NNNNNNNN-N
